<a href="https://colab.research.google.com/github/Santgupt/Python-Practice/blob/master/Pandas_Ch_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s1 = pd.Series([2, 3, 4, 5, 6])

s2 = pd.Series([7, 8, 9, 10, 11])

s3 = pd.Series([12, 13, 14, 15, 16])


In [ ]:
s1

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [ ]:
s2

0     7
1     8
2     9
3    10
4    11
dtype: int64

In [ ]:
s3

0    12
1    13
2    14
3    15
4    16
dtype: int64

In [ ]:
s1.append(s2)

0     2
1     3
2     4
3     5
4     6
0     7
1     8
2     9
3    10
4    11
dtype: int64

In [ ]:
s3.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s2.append(s3,ignore_index = True)

0     7
1     8
2     9
3    10
4    11
5    12
6    13
7    14
8    15
9    16
dtype: int64

In [ ]:
pd.concat([s1,s2])

0     2
1     3
2     4
3     5
4     6
0     7
1     8
2     9
3    10
4    11
dtype: int64

In [ ]:
pd.concat([s2,s3],ignore_index=True)

0     7
1     8
2     9
3    10
4    11
5    12
6    13
7    14
8    15
9    16
dtype: int64

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])


In [ ]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
type(df2)

pandas.core.frame.DataFrame

In [ ]:
df2.shape

(4, 4)

In [ ]:
df1.append(df2)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
pd.concat([df1,df2],axis=0)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
pd.concat([df1,df2],axis=1)

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [ ]:
d1 = pd.DataFrame(dict(A=.1, B=.2, C=.3), [2, 3])
d2 = pd.DataFrame(dict(B=.4, C=.5, D=.6), [1, 2])
d3 = pd.DataFrame(dict(A=.7, B=.8, D=.9), [1, 3])

In [ ]:
d1

A    B    C
2  0.1  0.2  0.3
3  0.1  0.2  0.3

In [ ]:
d2

B    C    D
1  0.4  0.5  0.6
2  0.4  0.5  0.6

In [ ]:
d3

A    B    D
1  0.7  0.8  0.9
3  0.7  0.8  0.9

In [ ]:
pd.concat([d1,d2,d3])

A    B    C    D
2  0.1  0.2  0.3  NaN
3  0.1  0.2  0.3  NaN
1  NaN  0.4  0.5  0.6
2  NaN  0.4  0.5  0.6
1  0.7  0.8  NaN  0.9
3  0.7  0.8  NaN  0.9

#Use **multi-index** on (d1, d2, d3 )rows

In [ ]:
d1.iloc[[0]]

A    B    C
2  0.1  0.2  0.3

In [ ]:
d1.iloc[0:2]

A    B    C
2  0.1  0.2  0.3
3  0.1  0.2  0.3

In [ ]:
d2.iloc[[1]]

B    C    D
2  0.4  0.5  0.6

In [ ]:
d3.iloc[0:3]

A    B    D
1  0.7  0.8  0.9
3  0.7  0.8  0.9

In [ ]:
pd.concat([d1,d2,d3],axis=1)

A    B    C    B    C    D    A    B    D
1  NaN  NaN  NaN  0.4  0.5  0.6  0.7  0.8  0.9
2  0.1  0.2  0.3  0.4  0.5  0.6  NaN  NaN  NaN
3  0.1  0.2  0.3  NaN  NaN  NaN  0.7  0.8  0.9

Use multi-index on (d1 ,d2, d3)columns


In [ ]:
d1.set_index('C')

A    B
C            
0.3  0.1  0.2
0.3  0.1  0.2

In [ ]:
d2.set_index(['B','C'])

D
B   C       
0.4 0.5  0.6
    0.5  0.6

In [ ]:
d3.set_index(['D','B','A'])

Empty DataFrame
Columns: []
Index: [(0.9, 0.8, 0.7), (0.9, 0.8, 0.7)]

In [ ]:
import numpy as np
import pandas as pd
A = np.arange(3).reshape(1,3) 
print(A)
B = np.arange(6).reshape(3,2)
print(B)
C = np.arange(9).reshape(3,3)
print(C)

[[0 1 2]]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
A

array([[0, 1, 2]])

In [ ]:
B

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.hstack((B,C))

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [ ]:
np.concatenate((B,C),axis = 1)

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [ ]:
np.vstack((A,C))

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.concatenate((A,C))

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])

In [ ]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
ar1 = np_array = df1.to_numpy()

In [ ]:
ar1

array([['A0', 'B0', 'C0', 'D0'],
       ['A1', 'B1', 'C1', 'D1'],
       ['A2', 'B2', 'C2', 'D2'],
       ['A3', 'B3', 'C3', 'D3']], dtype=object)

In [ ]:
ar2 = np_array = df2.to_numpy()

In [ ]:
ar2

array([['A4', 'B4', 'C4', 'D4'],
       ['A5', 'B5', 'C5', 'D5'],
       ['A6', 'B6', 'C6', 'D6'],
       ['A7', 'B7', 'C7', 'D7']], dtype=object)

In [ ]:
np.concatenate((ar1,ar2))

array([['A0', 'B0', 'C0', 'D0'],
       ['A1', 'B1', 'C1', 'D1'],
       ['A2', 'B2', 'C2', 'D2'],
       ['A3', 'B3', 'C3', 'D3'],
       ['A4', 'B4', 'C4', 'D4'],
       ['A5', 'B5', 'C5', 'D5'],
       ['A6', 'B6', 'C6', 'D6'],
       ['A7', 'B7', 'C7', 'D7']], dtype=object)

In [ ]:
pd.concat([df1,df2], join='inner')

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
pd.concat([df1,df2], join='outer')


A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7